module.exports = {
  apps: [
    {
      name: "backendSIRH",
      script: "src/index.js",
      watch: false,
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 4000,
      max_memory_restart: "1G",
      env: {
        NODE_ENV: "production",
      },
      env_development: {
        NODE_ENV: "development",
      },
      error_file: "logs/pm2-error.log",
      out_file: "logs/pm2-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      combine_logs: true,
      merge_logs: true,
    },
    {
      name: "extractor-xml",
      script: "./server.js",
      cwd: "C:/Users/ilesm/Documents/extractor_xml",
      instances: 1,
      exec_mode: "fork",
      watch: false,
      autorestart: true,
      max_restarts: 10,
      min_uptime: "10s",
      restart_delay: 4000,
      max_memory_restart: "500M",
      env: {
        NODE_ENV: "production",
        PORT: 3030,
      },
      error_file: "./logs/err-extractor.log",
      out_file: "./logs/out-extractor.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      combine_logs: true,
      merge_logs: true,
    },
  ],
};
